import React, {useEffect} from "react";
import {useSelector} from "react-redux";
import './BudgetOverview.scss';

function BudgetOverview(props) {
    const lastUpdate = 'Jan 08, 2022';
    const amountOfMoney = useSelector(state => state.budget.amountOfMoney);
    const totalIncome = useSelector(state => state.budget.totalIncome);
    const totalExpense = useSelector(state => state.budget.totalExpense);

    useEffect(() => {
        if (amountOfMoney > 0){
            document.getElementById("amountOfMoney").style.color = '#23d160';
        } else if (amountOfMoney < 0) {
            document.getElementById("amountOfMoney").style.color = '#ff3860';
        } else {
            document.getElementById("amountOfMoney").style.color = '#7a7a7a';
        }
    },[amountOfMoney]);
    return (
        <section className='section'>
            <div className='overview'>
                <h1 className='overview_title'>Budget Overview</h1>
                <h2 className='overview_subtitle'>Last update: {lastUpdate}</h2>
                <div className='overview_container'>
                    <div className='overview_container_details'>
                        <div className='overview_container_details_moneyLeft'>
                            <p><span className='overview_container_details_moneyLeft_amount' id='amountOfMoney'>$ {amountOfMoney.toFixed(2)}</span></p>
                            <p className='overview_container_details_moneyLeft_text'>Money Left</p>
                        </div>
                        <div className='overview_container_details_totalIncome'>
                            <p><span className='overview_container_details_totalIncome_amount'>$ {totalIncome.toFixed(2)}</span></p>
                            <p className='overview_container_details_totalIncome_text'>Total Income</p>
                        </div>
                        <div className='overview_container_details_totalExpense'>
                            <p><span className='overview_container_details_totalIncome_amount'>$ {totalExpense.toFixed(2)}</span></p>
                            <p className='overview_container_details_totalIncome_text'>Total Expense</p>
                        </div>
                    </div>
                    <div className='overview_container_chart'>
                        <p>Chart generated by Chart.JS will be there</p>
                    </div>
                </div>
            </div>
        </section>
    )
}

export default BudgetOverview;